site_name: scNavigator pipeline documentation
site_url: https://scn-pipeline.readthedocs.io/
nav:
    - Getting started: index.md
    - overview.md
    - dependency_dispatcher.md
    - meta.md
    - processing.md
    - analysis.md
theme: material
markdown_extensions:
  - pymdownx.highlight:
        anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
